### ISSUE TITLE
Problem with proxy autentication

### ISSUE THREAD

**Issue by juantimonescalona** [Appdynamics/AppDynamics.DEXTER#1]
Hi
I have a problem with proxy settings
https://github.com/Appdynamics/AppDynamics.DEXTER/wiki/Proxy-Settings

I add the block of proxy in my net471\AppDynamics.Dexter.exe.config
the original code of this config is:
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.1"/>
    </startup>
</configuration>`

i added the block system.net with the default proxy in the configuration block in my first try
i added the block system.net with the default proxy behind the configuration block in my second try

All time i obtain the same error using a correct job json:

dotnet exec netcoreapp2.0/AppDynamics.Dexter.dll -j jobs/eciJob1.json 
Checking input job file /home/jtimon/proyectos/ECI/DEXTER/jobs/eciJob1.json
Checking output folder /home/jtimon/AppD.Dexter.Out
Creating job output folder /home/jtimon/AppD.Dexter.Out/eciJob1
Processing input job file to output job file
Target [1] Controller ControllerApi: ControllerUrl='https://xxxxxxxxx.saas.appdynamics.com', UserName='yyy@xxxxxxxxx' not accessible
Job File Problem: Expanded targets but not a single valid target to work on
This is most likely caused by either incorrect password or incorrectly specified user name.
Only AppDynamics-internal authentication is supported in username@tenant format
If you are using SAML or LDAP account, please change to AppDynamics-internal account
Application execution took 00:00:00.6768887 (676 ms)

Regards

**Comment by danielodievich** [comment]
Hello there,

dotnetcore applications in netcoreapp2.0/ folder do not use the .NET Full framework config from net471\AppDynamics.Dexter.exe.config. Those are separate execution modes.

Read https://github.com/Appdynamics/AppDynamics.DEXTER/wiki/Proxy-Settings#net-core-framework-on-windows-on-mac, for workaround on setting system proxy on your mac/Linux machine.

Daniel

**Comment by danielodievich** [comment]
The instructions to get proxy on mac are in the docs
