### ISSUE TITLE
queryListData return clientName as null 

### ISSUE THREAD

**Issue by hwa123** [Appdynamics/AppDynamics.DEXTER#101]
**Describe the bug**
The controller/restui/databases/queryListData listed under ExtractDBEntities returns clientName as null.  

**Expected behavior**
It should return the client name same way as AppD UI did. 

**Screenshots**
```json
    {
        "duration": 44000.0,
        "hits": 0,
        "weight": 0.8026267785479752,
        "id": "2252487",
        "name": null,
        "namespace": null,
        "clientName": null,
        "queryHashCode": "cd9e58f320c7ee8e231488c6d84acbb23d51cd0b",
        "queryText": "\n some SQL queries here \n",
        "snapshotWindowData": false,
        "snapshotCorrelationData": false,
        "appId": 0,
        "appName": null
    }
```
**Desktop (please complete the following information):**
 - OS: mac os

**Comment by danielodievich** [comment]
Can you please clarify. Where do you want to see the ClientName?

ClientName is part of:
* Clients
* Sessions
* Queries

It appears to work in Clients and Sessions in one of my local tests. However, on the Queries, upon further examination, I don't think the Queries ever had this properly set as this data is never returned from the Controller when list of queries is returned.

Yes, the Query screen has a list of Clients, but DEXTER does not query for it. 
If you want to have that, please file an enhancement request.
