### ISSUE TITLE
Export Metrics data from Dashboard to Excel

### ISSUE THREAD

**Issue by jeromeguillaume** [Appdynamics/AppDynamics.DEXTER#102]
Hello,

Do you plan to export metrics data from Dashboard to Excel file?

I used Dexter and it exports only JSON config file and not metrics data.

Thanks

**Comment by danielodievich** [comment]
Hi Jerome!

I have no plans to export any time series from Dashboards. It is too wide ranging request. If you want to export metrics, you can do so with Entity Metrics report for APM Entities.

I *have* been considering taking a screenshot of the dashboard, though.

**Comment by danielodievich** [comment]
Will not implement
