### ISSUE TITLE
Health Rule Detailed Config

### ISSUE THREAD

**Issue by Sravan921** [Appdynamics/AppDynamics.DEXTER#103]
For Some Applications, we have used "Trigger only when violation occurs  4 times in the last 30 min(s)" feature in health rules. is it possible to pull that information through dexter ?

**Comment by danielodievich** [comment]
What do you want to pull? Configuration of the Health Rule? Or the triggered Events?

**Comment by Sravan921** [comment]
Configuration

**Comment by danielodievich** [comment]
The configuration is all in https://github.com/Appdynamics/AppDynamics.DEXTER/wiki/Configuration-Report

**Comment by Sravan921** [comment]
Sorry but it's not there. I checked Health Rules tab in Configuration report, it shows Warn/Critical Trigger No Data Column. 

<img width="1484" alt="Screen Shot 2020-04-21 at 5 21 58 PM" src="https://user-images.githubusercontent.com/23319526/79915275-add68f00-83f4-11ea-8d21-2b1b6d88458a.png">

I would like to see two things,
- Trigger only When violation occurs option enabled or not in the health rule. 
- What the value of it ? (i.e, number of times in within the time frame).

is it possible?

Thanks,
Sravan

**Comment by danielodievich** [comment]
Ah, I see.
That's a new feature that was introduced into the Controller after the parsing of Configuration was written. 
That value will be present in

**Comment by Sravan921** [comment]
Thanks a lot :)

**Comment by Sravan921** [comment]
Also, it looks like this report is potentially missing some Business Transaction health rules.  For a few applications, I see that the error rate and response time health rules show up but I don’t see the stall count health rule. Do you know why this might be happening?

**Comment by Sravan921** [comment]
![Stall](https://user-images.githubusercontent.com/23319526/80405106-27a4c780-8890-11ea-8f29-0e0b6e89490a.png)

Please see the attached screenshot.

**Comment by danielodievich** [comment]
Are you saying that the Business Transaction Stall - Alert is not in the Report? Really? Can you share the report and the configuration.xml from that application on the Data\<app>\CFG folder?

**Comment by Sravan921** [comment]
Apologies. It's actually there, I was using the wrong filter :P, Thanks for the prompt response.
