### ISSUE TITLE
DEXTER is not able to pull data at tier level

### ISSUE THREAD

**Issue by BondugulaAvinash** [Appdynamics/AppDynamics.DEXTER#104]
**Describe the bug**
Current DEXTER setup is working fine at the Application level, Tried to pull data at tier level, not working and pulling expected data. By this issue missing data visualization when trying at the node level.

**Expected behavior**
If there is any way or JSON file that can help me in pulling data as expected at a tier that would we helpful.

**Comment by danielodievich** [comment]
Can you please describe the issue in better detail. What do you want to pull at Tier level? What visualizations are you wanting to produce?

**Comment by danielodievich** [comment]
Can you clarify please?

**Comment by arunslalgit** [comment]
Same issue here. Dexter picks up data on an Application level only and cannot minimize the scope to a Tier level. Can anyone help here pls?

**Comment by arunslalgit** [comment]
@danielodievich danielodievich 

We would like to pull  "TransactionNode", "TransactionBackend", "TransactionBT", "TransactionSEP", "TransactionError", "TransactionIP", "AgentStats", "OSHardware", "CLRStats", "IISStats", "IISReqCounts", "IISReqPerf", "JVMStats", "BusinessTransactionPercentiles"

**Comment by danielodievich** [comment]
Hi, if you want to grab the Tier level only, you need to look at https://github.com/Appdynamics/AppDynamics.DEXTER/wiki/Metric-Sets. The entity type the metric set applies to is in EntityType column. If you want to pull only Tier metrics, you can remove all rows with EntityType that is NOT Tier and you'll accomplish what you want.
Alternatively, you can modify the MetricSet column value for just the Tier metrics you want and specify that.
Let me know if this makes sense.

**Comment by danielodievich** [comment]
Closing for lack of clarify
