### ISSUE TITLE
Enhancement Request: Add a date override at command line

### ISSUE THREAD

**Issue by Sarkie** [Appdynamics/AppDynamics.DEXTER#107]
**Describe the bug**
We want to automate Dexter to run every day, we want everything to be the same apart from the date duration.

Currently we'd have to manually edit the json file

**Expected behavior**
AppDynamics.Dexter.exe -j Example.JSON -df 2020-05-01 00:00 -dt 2020-05-01 01:00

**Comment by danielodievich** [comment]
The upcoming release of DEXTER will introduce the relative time ranges in the job file. Stay tuned.
