### ISSUE TITLE
Wiki Issue : Command Line Params

### ISSUE THREAD

**Issue by Sarkie** [Appdynamics/AppDynamics.DEXTER#108]
**Describe the bug**
Command Line Wiki is missing details

**To Reproduce**
1. Go to '.https://github.com/Appdynamics/AppDynamics.DEXTER/wiki/Command-Line-Parameters"

**Expected behavior**

  -j, --job-file                      Required. Input file defining the parameters of the ETL job to process.

  -o, --output-folder                 Output folder where to store results of processing.

  -c, --compare-states-file           Required. Compare file defining the mappings of the state comparison to perform.

  -l, --left-from-state-folder        Required. Folder of the ETL job to use as a left side/reference/from comparison.

  -r, --right-to-state-folder         Required. Folder of the ETL job to use as a right side/difference/to comparison.

  -d, --delete-previous-job-output    If true, delete any results of previous processing.

  -s, --sequential-processing         If true, process certain items during extraction and conversion sequentially.

  -v, --skip-version-check            If true, skips the version check against GitHub repository.

  --help                              Display this help screen.

  --version                           Display version information.

**Comment by danielodievich** [comment]
The Functionality behind -c and -l are not yet complete so they are not documented

**Comment by Sarkie** [comment]
@danielodievich ok cool, I was looking into using it, but not sure how to. Thanks!
