### ISSUE TITLE
PowerBI Issues

### ISSUE THREAD

**Issue by Sarkie** [Appdynamics/AppDynamics.DEXTER#109]
**Describe the bug**
Some reports won't load fully in Power BI

**To Reproduce**
1. Create a report
2. Load a BI Template
3. Some errors are shown in different reports

**Expected behavior**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/283203/81048192-bed2d600-8eb3-11ea-81e0-35dbf4c349e8.png)

**Comment by danielodievich** [comment]
Well, what ARE the errors? Have you looked?

Are you by any chance in a locale other then en-us? If yes, follow the steps https://github.com/Appdynamics/AppDynamics.DEXTER/wiki#adjust-power-bi-reports-to-your-locale to set the right locale for your machine.

**Comment by Sarkie** [comment]
@danielodievich I didn't know if there's much point looking if it was a kind of "this is just an added bonus of the release and not support" kind of thing.
I might be en-gb will verify, thanks.
