### ISSUE TITLE
Health Rule Violations for 24 months

### ISSUE THREAD

**Issue by Sravan921** [Appdynamics/AppDynamics.DEXTER#115]
Hi,

Is there any way to pull health rule violations for a single app from the past 24 months ? if yes could you please provide the job file configuration?

Thanks,
Sravan

**Comment by danielodievich** [comment]
Hi there,

Note that the health rule violations are not stored for a year. I believe the retention rate on all the events, including health rule violations, is 3 months.

However, if you want 
Input\Events=true, 
Input\EventsSelectionCriteria = ["POLICY_OPEN_WARNING", "POLICY_ETC", ...]
https://github.com/Appdynamics/AppDynamics.DEXTER/blob/master/ProcessingSteps/JobStepBase.cs#L151-L160
https://github.com/Appdynamics/AppDynamics.DEXTER/wiki/Job-File#eventsselectioncriteria-array-of-strings
Output=Events=true, 
TimeFrame (https://github.com/Appdynamics/AppDynamics.DEXTER/wiki/Job-File#timeframe) - you can do things like 
        "TimeFrame": {
            "MarkDate": "TODAY",
            "MarkTime": "NOW",
            "Duration": "-P1Y"
        },
Specify Target for that app
Everything else in Input to false.

**Comment by bhjelmar** [comment]
Closing as this is dependent on controller configuration settings, not Dexter.
