### ISSUE TITLE
Are the "Data" and "Index" folders necessary to display "Report"?

### ISSUE THREAD

**Issue by AlvaroBlueCross** [Appdynamics/AppDynamics.DEXTER#158]
I perform daily analysis and this has been a conflict with the client due to the disk memory used in the output files, I would like to know if, doing a debugging, **deleting the "Data" and "Index" folders**, I could correctly open the "Report" folder which is the only one the client is interested in, and thus reduce the amount of memory used.

Thank's

**Comment by danielodievich** [comment]
The Report folder is entirely self-contained so the Data and Index folders can be deleted.

**Comment by AlvaroBlueCross** [comment]
Thanks
