### ISSUE TITLE
Configuration Report - Add Error Config for the APM Application

### ISSUE THREAD

**Issue by danielodievich** [Appdynamics/AppDynamics.DEXTER#48]

**Comment by johnfaronson** [comment]
To better support REV application config reporting, please report the application config for BTs with the broken down by URL based rules [SERVLET, ASP_DOTNET] and Class based rules [POJO, POCO]. 

For the URL group please extract some part of the URL match string and put that into a column.
For the Class group please extract the class name and method like in custom exit rules for example.

**Comment by danielodievich** [comment]
Completed a while ago
