### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by rohitjangid96** [Appdynamics/AppDynamics.DEXTER#50]
This is my Appdynamics account : 
![image](https://user-images.githubusercontent.com/17066976/53340236-88540f80-392e-11e9-9ae7-f4488dab0e3f.png)

Here is the Screenshot when I'm trying to run DEXTER  : 
![image](https://user-images.githubusercontent.com/17066976/53340469-1af4ae80-392f-11e9-8792-7df8b2e02efa.png)

**Comment by edwardferron** [comment]
change your user name in the job file to rsignh16@eitappd

**Comment by rohitjangid96** [comment]
Tried everything,
rsingh16@eitappd,rsingh16@eitappd.cablevision.com,rsingh16@eitappd.cablevision.
but nothing is working. Giving same error

**Comment by danielodievich** [comment]
@rohitjangid96 Your username is rsingh16@_tenant_ where tenant is most likely customer1. See https://github.com/Appdynamics/AppDynamics.DEXTER/wiki/Job-File#username-string
