### ISSUE TITLE
Issue on Running Dexter - Release 1.0.0.36

### ISSUE THREAD

**Issue by GopiBava** [Appdynamics/AppDynamics.DEXTER#51]
Hi Team,

I was trying to run the appDynamics.Dexter Release 1.0.0.36 . But unfortunately i am getting error on the Event and Health Rule violations stage. If i sent Event as false in DefaultJob.Json file it skips the error and saves the file.

Is it possible to help me on this ETL to extract data from app Dynamics controller for powerBI reporting.

<img width="847" alt="capture" src="https://user-images.githubusercontent.com/42833625/53471644-519e0680-3aa0-11e9-9dac-9c79fc4b9d35.PNG">

Regards
Gopi Bava

**Comment by danielodievich** [comment]
Fixed by d26c4d64bb1dfb895a110ecf182ac7340e877d72
