### ISSUE TITLE
Move the Flame Graph / Chart Legend

### ISSUE THREAD

**Issue by Sarkie** [Appdynamics/AppDynamics.DEXTER#67]
**Describe the bug**
The Legend on the SVG is in the top right and many calls are hidden under it, so have to remove it in order to see it.

**To Reproduce**
1. Go to a Flame Graph / Chart
2. Legend is Top Right
3. Hides any method calls underneath

**Expected behavior**
The Legend should be outside of the region of the chart

**Screenshots**
Rather not as contains private information, but can in private

**Reports**
Rather not as contains private information, but can in private

**Comment by danielodievich** [comment]
Did you notice that there is a "Legend" word in upper right corner? If you click on it, the legend will hide and show as needed?

**Comment by Sarkie** [comment]
Version : 1.2.38.1 I have no legend.

And checking the source of the svg, I see no reference to Legend.

**Comment by danielodievich** [comment]
Ok, that makes sense. Legend is in build https://github.com/Appdynamics/AppDynamics.DEXTER/releases/tag/1.2.39.0. You can rerun your report in this build and you'll be able to collapse the legend away
