### ISSUE TITLE
Extract Metrics data from Synthetics jobs (EUM)

### ISSUE THREAD

**Issue by Vikkelso** [Appdynamics/AppDynamics.DEXTER#75]
Hi

It would be very useful if you also would be able to extract metrics from EUM and Synthetics jobs.
Then you don´t need to use several different programs to extract data from AppDynamics.

**Comment by kunwarjit** [comment]
@danielodievich , do you have an update? Keen to get metrics out from EUM and Synthetics.

**Comment by Vikkelso** [comment]
Hi

What is this related to ??


@danielodievich<https://urldefense.com/v3/__https:/github.com/danielodievich__;!!GNpmbAs!Wja0dy5LpYQZJopjYG4RnMXbB5rDnN5fmxIGI-2khK1xK5-Gksb5mhPpGUo$> , do you have an update? Keen to get metrics out from EUM and Synthetics.
/Carsten

Fra: Jit [mailto:notifications@github.com]
Sendt: 16. januar 2020 01:34
Til: Appdynamics/AppDynamics.DEXTER <AppDynamics.DEXTER@noreply.github.com>
Cc: Carsten Vikkelsø Jensen <cwj@tdc.dk>; Author <author@noreply.github.com>
Emne: [EXT] Re: [Appdynamics/AppDynamics.DEXTER] Metrics data from Synthetics jobs (EUM) (#75)

UK: Be aware, this is an external email and sender may not be genuine. If you are a TDC employee and this email seems suspicious, please forward it (as attachment) to "Sikkerhed (Koncern Sikkerhed)"
DK: Vær opmærksom på, at dette er en ekstern e-mail og afsender kan være forfalsket. Er du TDC ansat og virker mailen mistænkelig, så videresend den venligst (som vedhæftet fil) til "Sikkerhed (Koncern Sikkerhed)".


@danielodievich<https://urldefense.com/v3/__https:/github.com/danielodievich__;!!GNpmbAs!Wja0dy5LpYQZJopjYG4RnMXbB5rDnN5fmxIGI-2khK1xK5-Gksb5mhPpGUo$> , do you have an update? Keen to get metrics out from EUM and Synthetics.

**Comment by kunwarjit** [comment]
Wanted to know if this enhancement made its way to dexter roadmap as an enhancement

**Comment by danielodievich** [comment]
Hi there,

I would love to implement it, but it is unlikely to happen without a full services engagement with you that will pay for it. 

My focus recently has been on taking advantage of data model to build a comprehensive health check.

**Comment by dodegaard** [comment]
@danielodievich I am willing to collaborate with you on making this happen.  Would that be possible?  I am a customer of AppDynamics and a .NET Developer.  Thanks for the consideration.

**Comment by danielodievich** [comment]
I started writing extraction for all kinds of metrics - not just APM - last week. I already have BIQ, DB and 1/2 of WEB working. I will add MOBILE and SIM shortly. Should be released in a couple of weeks.

**Comment by dodegaard** [comment]
That is great news!  I saw some of the WEB stuff and got excited until i saw this issue.  Thank you for your efforts and happy to test it once you have it in place.  I have a 20.7 controller as of tomorrow night (SaaS).

**Comment by danielodievich** [comment]
Good to hear that you can test. I'll let you know!

**Comment by Vikkelso** [comment]
Hi

Is there any updates to this ?

/Carsten

Fra: Daniel Odievich <notifications@github.com>
Sendt: 14. juli 2020 01:00
Til: Appdynamics/AppDynamics.DEXTER <AppDynamics.DEXTER@noreply.github.com>
Cc: Carsten Vikkelsø Jensen <cwj@tdc.dk>; Author <author@noreply.github.com>
Emne: [EXT] Re: [Appdynamics/AppDynamics.DEXTER] Extract Metrics data from Synthetics jobs (EUM) (#75)

UK: Be aware, this is an external email and sender may not be genuine. If you are a TDC employee and this email seems suspicious, please forward it (as attachment) to "Sikkerhed (Koncern Sikkerhed)"
DK: Vær opmærksom på, at dette er en ekstern e-mail og afsender kan være forfalsket. Er du TDC ansat og virker mailen mistænkelig, så videresend den venligst (som vedhæftet fil) til "Sikkerhed (Koncern Sikkerhed)".


I started writing extraction for all kinds of metrics - not just APM - last week. I already have BIQ, DB and 1/2 of WEB working. I will add MOBILE and SIM shortly. Should be released in a couple of weeks.

-

**Comment by danielodievich** [comment]
Thanks for following up. I have metrics from everything extracted working. 
I am starting work on creating reports for WEB, MOBILE, DB, BIQ and SIM today. I am only working on this part time so it's going to be a couple more weeks...
