### ISSUE TITLE
BIQ processing error, can lead to NullReferenceException

### ISSUE THREAD

**Issue by KierDran** [Appdynamics/AppDynamics.DEXTER#76]
Error text:
Experience Levels
System.NullReferenceException: Object reference not set to an instance of an object.
   at AppDynamics.Dexter.ProcessingSteps.IndexBIQEntities.Execute(ProgramOptions programOptions, JobConfiguration jobConfiguration) in C:\appdynamics\AppDynamics.DEXTER\src\ProcessingSteps\Index\IndexBIQEntities.cs:line 474

Description:
Looks like a cut-paste error from the business journeys moving into the experience level section. The line references the businessJourneysList list instead of the experienceLevelsList list.

error line:
stepTimingTarget.NumEntities = stepTimingTarget.NumEntities + businessJourneysList.Count;
Fix:
stepTimingTarget.NumEntities = stepTimingTarget.NumEntities + experienceLevelsList.Count;

**Comment by danielodievich** [comment]
Sure looks like a copy&paste error. Thank you for finding it.
