### ISSUE TITLE
Enhancement Request: Pull Error detection rules

### ISSUE THREAD

**Issue by sachanta** [Appdynamics/AppDynamics.DEXTER#77]
Wells Fargo wants to periodically verify the custom 'Error Detection' rules added by users for any performance issues(such as, check for *.* in regular expressions).

We would like to use Dexter to grab this data, so that, users can add additional checks on these.

**Comment by danielodievich** [comment]
Fixed in dc0d5752bf4e7e19935429417347e32a85138ca5
