### ISSUE TITLE
Error reading JArray from JsonReader

### ISSUE THREAD

**Issue by davidskeen** [Appdynamics/AppDynamics.DEXTER#85]
Ran a report pulling all SIM metrics on a prod controller for 1 hour. Hit this error:

ExtractSIMEntities(21): [1/2], https://karauctionservices-nonprod.saas.appdynamics.com Server & Infrastructure Monitoring duration 00:06:05.3753495 (365375 ms)
ExtractSIMEntities(21): [2/2], https://karauctionservices-prod.saas.appdynamics.com Server & Infrastructure Monitoring(29) [SIM]
List of Tiers
List of Nodes
List of Groups
List of Service Availability
Service Availability Details (0 entities)
Completed 0 Service Availabilities
List of Machines
Newtonsoft.Json.JsonReaderException: Error reading JArray from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JArray.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JArray.Parse(String json, JsonLoadSettings settings)
   at AppDynamics.Dexter.ProcessingSteps.ExtractSIMEntities.Execute(ProgramOptions programOptions, JobConfiguration jobConfiguration) in C:\appdynamics\AppDynamics.DEXTER\src\ProcessingSteps\Extract\ExtractSIMEntities.cs:line 145
ExtractSIMEntities(21): [2/2], https://karauctionservices-prod.saas.appdynamics.com Server & Infrastructure Monitoring duration 00:01:10.4383512 (70438 ms)
ExtractSIMEntities(21): total duration 00:07:15.8349648 (435834 ms)
If you need support, please check how to get it at https://github.com/Appdynamics/AppDynamics.DEXTER/wiki#getting-support
Application execution took 00:08:01.5795372 (481579 ms)
[logs.zip](https://github.com/Appdynamics/AppDynamics.DEXTER/files/3795709/logs.zip)

[all-sim-1031-1300.txt](https://github.com/Appdynamics/AppDynamics.DEXTER/files/3795716/all-sim-1031-1300.txt)

**Comment by danielodievich** [comment]
That call retrieves a LOT of machines 7580 items. The code ran in debugger and parses the list just great

**Comment by danielodievich** [comment]
I can't make it break. 
But I added some error handling around it for times when it breaks

**Comment by davidskeen** [comment]
I reduced the number of machines and generated a report successfully; not sure if there's anything further to do on this issue.
[all-sim-1101-0700.txt](https://github.com/Appdynamics/AppDynamics.DEXTER/files/3798244/all-sim-1101-0700.txt)
