### ISSUE TITLE
In the "Report" folder I only see StepDurations.csv 

### ISSUE THREAD

**Issue by johncbp** [Appdynamics/AppDynamics.DEXTER#90]
Hi,

In the "Report" folder I only see StepDurations.csv and I can't find the other files to generate the reports. 

I appreciate your help,

Thanks.

**Comment by danielodievich** [comment]
Can you upload logs https://github.com/Appdynamics/AppDynamics.DEXTER/wiki/Log-Files to show us what happened? Clearly the job didn't finish.

**Comment by Sravan921** [comment]
I'm getting same error, not able to generate any reports using the latest version of dexter.

**Comment by danielodievich** [comment]
Please send job file and logs. Can't help without them.

**Comment by mhenderly** [comment]
In the reports section, I am seeing it create a folder for the Excel file, not the file.

![image](https://user-images.githubusercontent.com/50489792/72092362-2733f100-32e0-11ea-9d1a-c55a0342a4a4.png)


Saving Excel report C:\AppD.Dexter.Out\SaaSTest-Reduced-10-2019\Report\kemper-test.saas\KA - AgentIn.2813\SEP\MetricGraphs.SEP.kemper-test.saas.KA - AgentIn.2813.201910010400-201911010400.xlsx
Unable to save Excel file C:\AppD.Dexter.Out\SaaSTest-Reduced-10-2019\Report\kemper-test.saas\KA - AgentIn.2813\APP\MetricGraphs.APP.kemper-test.saas.KA - AgentIn.2813.201910010400-201911010400.xlsx
Report Metric Graphs Metrics for Errors (11 entities, 744 timeranges)
Unable to save Excel file C:\AppD.Dexter.Out\SaaSTest-Reduced-10-2019\Report\kemper-test.saas\KA - AgentIn.2813\BT\MetricGraphs.BT.kemper-test.saas.KA - AgentIn.2813.201910010400-201911010400.xlsx
ERR CallsAndResponse starting for 11 entities [0].Unable to save Excel file C:\AppD.Dexter.Out\SaaSTest-Reduced-10-2019\Report\kemper-test.saas\KA - AgentIn.2813\BACK\MetricGraphs.BACK.kemper-test.saas.KA - AgentIn.2813.201910010400-201911010400.xlsx
ERR CallsAndResponse complete
Saving Excel report C:\AppD.Dexter.Out\SaaSTest-Reduced-10-2019\Report\kemper-test.saas\KA - AgentIn.2813\TIER\MetricGraphs.TIER.kemper-test.saas.KA - AgentIn.2813.201910010400-201911010400.xlsx

Saving Excel report C:\AppD.Dexter.Out\SaaSTest-Reduced-10-2019\Report\kemper-test.saas\KA - AgentIn.2813\NODE\MetricGraphs.NODE.kemper-test.saas.KA - AgentIn.2813.201910010400-201911010400.xlsx
Unable to save Excel file C:\AppD.Dexter.Out\SaaSTest-Reduced-10-2019\Report\kemper-test.saas\KA - AgentIn.2813\SEP\MetricGraphs.SEP.kemper-test.saas.KA - AgentIn.2813.201910010400-201911010400.xlsx
Saving Excel report C:\AppD.Dexter.Out\SaaSTest-Reduced-10-2019\Report\kemper-test.saas\KA - AgentIn.2813\ERR\MetricGraphs.ERR.kemper-test.saas.KA - AgentIn.2813.201910010400-201911010400.xlsx
Unable to save Excel file C:\AppD.Dexter.Out\SaaSTest-Reduced-10-2019\Report\kemper-test.saas\KA - AgentIn.2813\ERR\MetricGraphs.ERR.kemper-test.saas.KA - AgentIn.2813.201910010400-201911010400.xlsx
Unable to save Excel file C:\AppD.Dexter.Out\SaaSTest-Reduced-10-2019\Report\kemper-test.saas\KA - AgentIn.2813\TIER\MetricGraphs.TIER.kemper-test.saas.KA - AgentIn.2813.201910010400-201911010400.xlsx
Unable to save Excel file C:\AppD.Dexter.Out\SaaSTest-Reduced-10-2019\Report\kemper-test.saas\KA - AgentIn.2813\NODE\MetricGraphs.NODE.kemper-test.saas.KA - AgentIn.2813.201910010400-201911010400.xlsx

**Comment by danielodievich** [comment]
I already noticed this and fixed it in the next upcoming build. For now, the Metric Graphs report is broken - there isn't anything you can do to work around that.

**Comment by Sravan921** [comment]
> I already noticed this and fixed it in the next upcoming build. For now, the Metric Graphs report is broken - there isn't anything you can do to work around that.

Is it fixed ? I'm getting same error.

OpenQA.Selenium.WebDriverException: unknown error: Chrome failed to start: exited normally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options)
   at AppDynamics.Dexter.ProcessingSteps.ExtractAPMEntityDashboardScreenshots.Execute(ProgramOptions programOptions, JobConfiguration jobConfiguration) in C:\appdynamics\AppDynamics.DEXTER\src\ProcessingSteps\Extract\ExtractAPMEntityDashboardScreenshots.cs:line 179

**Comment by danielodievich** [comment]
The call stack you are showing is not from Entity Metric Graphs report. That is fixed, will be released next week

**Comment by danielodievich** [comment]
Fixed in https://github.com/Appdynamics/AppDynamics.DEXTER/commit/8659a926954337413ea08d1e58dd343b3cbf2cbc
