### ISSUE TITLE
Xslx file creation not working in 1.2.46 on linix

### ISSUE THREAD

**Issue by nucahx** [Appdynamics/AppDynamics.DEXTER#95]
**Describe the bug**
When  using the tool to generate Excel files it creates directories instead of files on linux.  It works fine in 1.2.42
**To Reproduce**
Run any report in linux

**Expected behavior**
Result xslx files in specified output folder.   Instead we get a directory of the filename.

**Screenshots**
I cant no provide no git hub access on site.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] linux
 - .NET Framework Type (Full/Core) core 
 - .NET/.NET Core Framework Version 

**Logs**

**Reports**
Include any produced reports that you have issues with

**Comment by danielodievich** [comment]
I have already fixed it and it will be released in 1.2.47.0

It was a dumb mistake with directory creation refactoring. Sorry!
