### ISSUE TITLE
Job File Time Range - Add dynamic date variable

### ISSUE THREAD

**Issue by lowrencekurera** [Appdynamics/AppDynamics.DEXTER#96]
Hi Team,

This tool is really great and we use to extract data from AppD. I'm planning to automate this process by providing a date variable instead of manual date change. So that I can schedule this job to be executed automatically for daily reporting. 

Can I do something like that? or is there a way that I could do similar?

ex: 
    var startd = new Date().toISOString();
    var varDate = startd.toJSON().slice(0,10);

"From": varDate+"T09:00:00"
"To": varDate+"T10:00:00"

**Comment by EulerOperator** [comment]
I'd like to see the following new features for managing time frames:

1) Allow both start / stop OR start / duration time specs.  In the job file, support From, To and Duration.  Use ISO-8601 specs for specifying duration.

2) Allow start or stop time to accept a special moniker for @NOW (or similar) that substitutes the current time.

3) Allow simple time arithmetic:  @NOW - P2H   Use a time that is two hours ago.  This allows for the following:
