### ISSUE TITLE
Cannot compile project, source files are missing.

### ISSUE THREAD

**Issue by zbrkic** [Appdynamics/AppDynamics.DEXTER#97]
Cannot compile project, source files are missing.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS2001	Source file 'C:\Projects\AppDynamics.DEXTER\ProcessingSteps\Report\ReportAPMIndividualApplicationAndEntityDetails.cs' could not be found.	AppDynamics.Dexter	C:\Projects\AppDynamics.DEXTER\CSC	1	Active
Error	CS2001	Source file 'C:\Projects\AppDynamics.DEXTER\ProcessingSteps\Report\ReportEventsAndHealthRuleViolations.cs' could not be found.	AppDynamics.Dexter	C:\Projects\AppDynamics.DEXTER\CSC	1	Active
...
```

**Comment by danielodievich** [comment]
That's weird. They are right in the source tree. Which branch did you clone?

**Comment by zbrkic** [comment]
I am on master branch and can't find _ReportAPMIndividualApplicationAndEntityDetails.cs_ here: https://github.com/Appdynamics/AppDynamics.DEXTER/find/master

**Comment by danielodievich** [comment]
Wait a minute? Are you trying to compile AppDynamics.Dexter.csproj? That's been replaced. Please compile AppDynamics.Dexter.Core.csproj instead.

**Comment by zbrkic** [comment]
Yes, Core is compiling successfully. Thanks.

**Comment by danielodievich** [comment]
Fantastic. Note that a new release will be out in a week or two with bunches of improvements and a few bug fixes
