### ISSUE TITLE
Resources missing in v1.2.46.0

### ISSUE THREAD

**Issue by tikkaman6555** [Appdynamics/AppDynamics.DEXTER#99]
AppDynamics.DEXTER\ProcessingSteps\Report\ReportAPMIndividualApplicationAndEntityDetails.cs
AppDynamics.DEXTER\ProcessingSteps\Report\ReportEventsAndHealthRuleViolations.cs
AppDynamics.DEXTER\ReportObjects\Configuration\AgentCallGraphSetting.cs
AppDynamics.DEXTER\ReportObjects\Configuration\AgentConfigurationProperty.cs
AppDynamics.DEXTER\ReportObjects\Configuration\BackendDiscoveryRule.cs
AppDynamics.DEXTER\ReportObjects\Configuration\BusinessTransactionDiscoveryRule.cs
AppDynamics.DEXTER\ReportObjects\Configuration\BusinessTransactionDiscoveryRule20.cs
AppDynamics.DEXTER\ReportObjects\Configuration\BusinessTransactionEntryRule.cs
AppDynamics.DEXTER\ReportObjects\Configuration\BusinessTransactionEntryRule20.cs
AppDynamics.DEXTER\ReportObjects\Configuration\BusinessTransactionEntryScope.cs
AppDynamics.DEXTER\ReportObjects\Configuration\ConfigurationEntityBase.cs
AppDynamics.DEXTER\ReportObjects\Configuration\ControllerSetting.cs
AppDynamics.DEXTER\ReportObjects\Configuration\CustomExitRule.cs
AppDynamics.DEXTER\ReportObjects\Configuration\DeveloperModeNode.cs
AppDynamics.DEXTER\ReportObjects\Configuration\EntityApplicationConfiguration.cs
AppDynamics.DEXTER\ReportObjects\Configuration\EntityBusinessTransactionConfiguration.cs
AppDynamics.DEXTER\ReportObjects\Configuration\EntityTierConfiguration.cs
AppDynamics.DEXTER\ReportObjects\Configuration\HTTPDataCollector.cs
AppDynamics.DEXTER\ReportObjects\Configuration\HealthRule.cs
AppDynamics.DEXTER\ReportObjects\Configuration\InformationPointRule.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\AgentCallGraphSettingReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\AgentConfigurationPropertyReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\BackendDiscoveryRuleReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\BusinessTransactionDiscoveryRule20ReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\BusinessTransactionDiscoveryRuleReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\BusinessTransactionEntryRule20ReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\BusinessTransactionEntryRuleReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\BusinessTransactionEntryScopeReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\ControllerSettingReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\CustomExitRuleReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\DeveloperModeNodeReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\EntityApplicationConfigurationReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\EntityBusinessTransactionConfigurationReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\EntityTierConfigurationReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\HTTPDataCollectorReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\HealthRuleReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\InformationPointRuleReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\MethodInvocationDataCollectorReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\Maps\ServiceEndpointEntryRuleReportMap.cs
AppDynamics.DEXTER\ReportObjects\Configuration\MethodInvocationDataCollector.cs
AppDynamics.DEXTER\ReportObjects\Configuration\ServiceEndpointEntryRule.cs
AppDynamics.DEXTER\ReportObjects\Database\DBApplication.cs
AppDynamics.DEXTER\ReportObjects\Database\DBBlockingSession.cs
AppDynamics.DEXTER\ReportObjects\Database\DBBusinessTransaction.cs
AppDynamics.DEXTER\ReportObjects\Database\DBClient.cs
AppDynamics.DEXTER\ReportObjects\Database\DBCollector.cs
AppDynamics.DEXTER\ReportObjects\Database\DBCollectorDefinition.cs
AppDynamics.DEXTER\ReportObjects\Database\DBDatabase.cs
AppDynamics.DEXTER\ReportObjects\Database\DBEntityBase.cs
AppDynamics.DEXTER\ReportObjects\Database\DBModule.cs
AppDynamics.DEXTER\ReportObjects\Database\DBProgram.cs
AppDynamics.DEXTER\ReportObjects\Database\DBQuery.cs
AppDynamics.DEXTER\ReportObjects\Database\DBSession.cs
AppDynamics.DEXTER\ReportObjects\Database\DBUser.cs
AppDynamics.DEXTER\ReportObjects\Database\DBWaitState.cs
AppDynamics.DEXTER\ReportObjects\Database\Maps\DBApplicationReportMap.cs
AppDynamics.DEXTER\ReportObjects\Database\Maps\DBBlockingSessionReportMap.cs
AppDynamics.DEXTER\ReportObjects\Database\Maps\DBBusinessTransactionReportMap.cs
AppDynamics.DEXTER\ReportObjects\Database\Maps\DBClientReportMap.cs
AppDynamics.DEXTER\ReportObjects\Database\Maps\DBCollectorDefinitionReportMap.cs
AppDynamics.DEXTER\ReportObjects\Database\Maps\DBCollectorReportMap.cs
AppDynamics.DEXTER\ReportObjects\Database\Maps\DBDatabaseReportMap.cs
AppDynamics.DEXTER\ReportObjects\Database\Maps\DBModuleReportMap.cs
AppDynamics.DEXTER\ReportObjects\Database\Maps\DBProgramReportMap.cs
AppDynamics.DEXTER\ReportObjects\Database\Maps\DBQueryReportMap.cs
AppDynamics.DEXTER\ReportObjects\Database\Maps\DBSessionReportMap.cs
AppDynamics.DEXTER\ReportObjects\Database\Maps\DBUserReportMap.cs
AppDynamics.DEXTER\ReportObjects\Database\Maps\DBWaitStateReportMap.cs
AppDynamics.DEXTER\ReportObjects\Entity\APMApplication.cs
AppDynamics.DEXTER\ReportObjects\Entity\APMEntityBase.cs
AppDynamics.DEXTER\ReportObjects\Entity\APMNode.cs
AppDynamics.DEXTER\ReportObjects\Entity\APMTier.cs
AppDynamics.DEXTER\ReportObjects\Entity\Backend.cs
AppDynamics.DEXTER\ReportObjects\Entity\BusinessTransaction.cs
AppDynamics.DEXTER\ReportObjects\Entity\Error.cs
AppDynamics.DEXTER\ReportObjects\Entity\InformationPoint.cs
AppDynamics.DEXTER\ReportObjects\Entity\Maps\APMApplicationReportMap.cs
AppDynamics.DEXTER\ReportObjects\Entity\Maps\APMNodeReportMap.cs
AppDynamics.DEXTER\ReportObjects\Entity\Maps\APMTierReportMap.cs
AppDynamics.DEXTER\ReportObjects\Entity\Maps\BackendReportMap.cs
AppDynamics.DEXTER\ReportObjects\Entity\Maps\BusinessTransactionReportMap.cs
AppDynamics.DEXTER\ReportObjects\Entity\Maps\ControllerReportMap.cs
AppDynamics.DEXTER\ReportObjects\Entity\Maps\ErrorReportMap.cs
AppDynamics.DEXTER\ReportObjects\Entity\Maps\InformationPointReportMap.cs
AppDynamics.DEXTER\ReportObjects\Entity\Maps\NodePropertyReportMap.cs
AppDynamics.DEXTER\ReportObjects\Entity\Maps\ResolvedBackendReportMap.cs
AppDynamics.DEXTER\ReportObjects\Entity\Maps\ServiceEndpointReportMap.cs
AppDynamics.DEXTER\ReportObjects\Entity\NodeProperty.cs
AppDynamics.DEXTER\ReportObjects\Entity\ResolvedBackend.cs
AppDynamics.DEXTER\ReportObjects\Entity\ServiceEndpoint.cs
AppDynamics.DEXTER\ReportObjects\Event\Maps\ApplicationEventReportMap.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\Machine.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\MachineCPU.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\MachineContainer.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\MachineNetwork.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\MachineProcess.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\MachineProperty.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\MachineVolume.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\Maps\MachineCPUReportMap.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\Maps\MachineContainerReportMap.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\Maps\MachineNetworkReportMap.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\Maps\MachineProcessReportMap.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\Maps\MachinePropertyReportMap.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\Maps\MachineReportMap.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\Maps\MachineVolumeReportMap.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\Maps\SIMApplicationReportMap.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\Maps\SIMNodeReportMap.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\Maps\SIMTierReportMap.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\SIMApplication.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\SIMEntityBase.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\SIMNode.cs
AppDynamics.DEXTER\ReportObjects\ServerInfrastructure\SIMTier.cs
AppDynamics.DEXTER\ReportObjects\Snapshot\Maps\MethodCallLineOccurrenceReportMap.cs

**Comment by danielodievich** [comment]
Do not run AppDynamics.Dexter.csproj. Compile AppDynamics.Dexter.Core.csproj

I am deleting that old csproj file now

**Comment by tikkaman6555** [comment]
cool thanks Daniel. I figured it must be deprecated but it was it's still included :)
